version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  identity-svc:
    image: kcrnac/dotnet-identity:latest
    build:
      context: .
      dockerfile: src/identityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Identity=Server=postgres:5432;User Id=postgres;Password=postgres;Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
